const DATARANGE_SAMPLE = "sample"
const DATARANGE_DAY = "day"
const DATARANGE_WEEK = "week"
const DATARANGE_MONTH = "month"

const REQUESTTYPE_FIRST = "first-time"
const REQUESTTYPE_CACHE = "cache-only"
const REQUESTTYPE_NEW = "new-only"

const WIDGETTYPE_SINGLE = "single-value"
const WIDGETTYPE_MULTI = "multi-value"

const HORIZONTAL_BUCKETING_MILLISECONDS = 60000
const VERTICAL_BUCKETING_MILLISECONDS = 60000

export default {
    DATARANGE_SAMPLE,
    DATARANGE_DAY,
    DATARANGE_WEEK,
    DATARANGE_MONTH,
    REQUESTTYPE_FIRST,
    REQUESTTYPE_CACHE,
    REQUESTTYPE_NEW,
    WIDGETTYPE_SINGLE,
    WIDGETTYPE_MULTI,
    HORIZONTAL_BUCKETING_MILLISECONDS,
    VERTICAL_BUCKETING_MILLISECONDS
}